import 'package:flutter/material.dart';

class MyQrGensTab extends StatelessWidget {
  const MyQrGensTab({super.key});

  @override
  Widget build(BuildContext context) {
    // Example data: Map of MSP (Most Selling Product) to number of QR codes generated
    final Map<String, int> qrData = {
      'Product A': 12,
      'Product B': 8,
      'Product C': 5,
      'Product D': 3,
    };

    final int maxValue = qrData.values.isNotEmpty ? qrData.values.reduce((a, b) => a > b ? a : b) : 1;

    return Padding(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          const Text(
            'QR Codes Generated by Most Selling Product',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 24),
          // Simple bar chart
          ...qrData.entries.map((entry) {
            final barWidth = (entry.value / maxValue) * 200;
            return Padding(
              padding: const EdgeInsets.symmetric(vertical: 8.0),
              child: Row(
                children: [
                  SizedBox(
                    width: 100,
                    child: Text(entry.key, style: const TextStyle(fontSize: 16)),
                  ),
                  Stack(
                    children: [
                      Container(
                        width: 200,
                        height: 24,
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                      Container(
                        width: barWidth,
                        height: 24,
                        decoration: BoxDecoration(
                          color: const Color(0xFFED6F1D),
                          borderRadius: BorderRadius.circular(8),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(width: 12),
                  Text('${entry.value}', style: const TextStyle(fontWeight: FontWeight.bold)),
                ],
              ),
            );
          }).toList(),
          const SizedBox(height: 24),
          const Text(
            'This chart shows the number of QR codes you have generated for each of your most selling products.',
            style: TextStyle(color: Colors.grey),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}